info:
  app:
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    name: '@project.name@'
    version: '@project.version@'

spring:
  profiles:
    active: prod  # Cambiado a prod
  application:
    name: com-ragnax-sanbernardo-notificacion

  # Configuración de Multi-Datasource (ajustado a tus nuevas tablas)
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/imsb?useSSL=false&allowPublicKeyRetrieval=true
      username: dbimsb
      password: "FTj$#88*"
      driver-class-name: com.mysql.cj.jdbc.Driver
    usuarios:
      jdbc-url: jdbc:mysql://localhost:3306/ragnax_usuariov1?useSSL=false&allowPublicKeyRetrieval=true
      username: dbimsb
      password: "FTj$#88*"
      driver-class-name: com.mysql.cj.jdbc.Driver

  hikari:
    maximum-pool-size: 10
    minimum-idle: 5

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect # Optimizado para MariaDB AWS

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # Configuración de Mail (Resend)
  mail:
    host: smtp.resend.com
    port: 465
    username: resend
    password: re_UNjdbpTp_GF4LZDirLGtHe9LDy2TojzhR
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
        socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory

server:
  port: 9999

logging:
  level:
    com.itextpdf.html2pdf.css.apply.util.FlexApplierUtil: ERROR
  file:
    name: spring_app.log
    path: /var/www/sb_ope_001a/logs/ # Asegúrate de crear esta carpeta en EC2

archivo:
  excel:
    nombreCarpetaUpload: /var/www/sb_ope_001a/public_sftp/1_upload/
    nombreCarpetaNormalizada: /var/www/sb_ope_001a/public_sftp/3_normalizado/
    nombreCarpetaMerge: /var/www/sb_ope_001a/public_sftp/4_merge/
    nombreArchivoNormalizadaCobranza: "Cobranza_ToNormalize.xlsx"
    nombreHojaUploadCobranza: Hoja1
    nombreHojaNormalizadaCobranza: ToNormalize
    nombreHojaMergeCobranza: Procesar

  html:
    nombreCarpetaTemplate: templates/
    nombreArchivoNotificacionV2: cartas/notificacion/notificacion_carta_v2.html
    # ... (mantener las rutas de logos relativas a resources/templates)

  creacion:
    # RUTAS ABSOLUTAS PARA LINUX/AWS
    carpeta: /var/www/sb_ope_001a/public_sftp/
    respaldo: /var/www/sb_ope_001a/public_sftp/2_backup/
    respaldoNormalizado: /var/www/sb_ope_001a/public_sftp/5_procesado/
    adjuntos:
      subCarpetaNormalizado: 3_normalizado/
      subCarpetaMerge: 4_merge/
      subCarpetaCobranza: 6_cobranza/
      subCarpetaNotificacion: 7_notificacion/
      nombreArchivoConsolidado: consolidado.pdf
      nombreArchivoReporte: reporte.pdf