spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        # Esto es vital para evitar el error de metadatos si una conexión tarda
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MariaDBDialect
#prod es prod
datasource:
  primary:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/imsb_prod?useSSL=false&allowPublicKeyRetrieval=true
    username: dbimsb
    password: "FTj$#88*"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  usuarios:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/ragnax_usuario_prod?useSSL=false&allowPublicKeyRetrieval=true
    username: dbimsb
    password: "FTj$#88*"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

server:
  port: 80

logging:
  level:
    com.itextpdf.html2pdf.css.apply.util.FlexApplierUtil: ERROR
  file:
    name: spring_app.log
    path: /var/www/sb_ope_001a/logs/ # Asegúrate de crear esta carpeta en EC2

archivo:
  excel:
    nombreCarpetaUpload: /var/www/sb_ope_001a/public_sftp/1_upload/
    nombreCarpetaNormalizada: /var/www/sb_ope_001a/public_sftp/3_normalizado/
    nombreCarpetaMerge: /var/www/sb_ope_001a/public_sftp/4_merge/

  creacion:
    # RUTAS ABSOLUTAS PARA LINUX/AWS
    carpeta: /var/www/sb_ope_001a/public_sftp/
    respaldo: /var/www/sb_ope_001a/public_sftp/2_backup/
    respaldoNormalizado: /var/www/sb_ope_001a/public_sftp/5_procesado/